name: R Lint

on:
  push:
  pull_request:

jobs:
  lintr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install lintr
        run: R -q -e 'install.packages("lintr", repos = "https://cloud.r-project.org")'
      - name: Lint scripts/R
        run: R -q -e 'lintr::lint_dir("scripts/R"); q(status = if (length(lintr::lint_dir("scripts/R"))>0) 1 else 0)'
